### PR TITLE
Ensure that the definitions window has the focus

### PR DESCRIPTION
**Pull request by samth**
Thanks to @rfindler for the help in tracking this down.

### CODE REVIEW

**Comment by Metaxal** [comment]
Thank you very much!

**Comment by samth** [comment]
I think more calls to set the focus are needed before each of the other string-inserts, because the later tests are still failing. http://drdr.racket-lang.org/60887/cs/racket/share/pkgs/quickscript-test/drracket.rkt

**Comment by Metaxal** [comment]
I've added a few more forced focus, we'll see if that works (I still haven't been able to reproduce the failure)

**Comment by rfindler** [comment]
Sam and I had a separate discussion somewhere along the way and reminded me that tests that rely on the keyboard focus won't work, in general, on drdr, because there might be multiple GUI tests running at once and any one can steal the focus from others. So it is probably best to not rely on the focus in any tests, instead.

**Comment by Metaxal** [comment]
Is there a way to 'semaphore' these tests? I suppose drdr could run non-gui tests in parallel

**Comment by Metaxal** [comment]
FTR: @samth says the tests appear to be fixed on drdr, so all is good for now.

**Comment by rfindler** [comment]
I think the idea is that running the tests sequentially is bad because it
would be a bottleneck.

It shouldn't be troublesome to avoid depending on the focus. Just send
keystrokes to a specific window instead of the window with the focus.

Robby

**Comment by Metaxal** [comment]
Oh, that should be the right approach indeed, I don't know why I didn't think of that. Thanks!

**Pull request merged**
